Task 1
ampp8800/calculator pull request #3
Opened 2021-08-01 10:05 UTC by ampp8800

check code

2021-08-01 10:19 UTC, EitherNor commented
<img width="747" alt="image" src="https://user-images.githubusercontent.com/19414663/127767409-34ea778a-eb05-4566-99e2-0ef742815751.png">

2021-08-01 10:23 UTC, EitherNor commented
<img width="161" alt="image" src="https://user-images.githubusercontent.com/19414663/127767521-2bbbd489-8f7a-4924-9435-764bce5ada6c.png">

2021-08-01 10:25 UTC, EitherNor commented
<img width="165" alt="image" src="https://user-images.githubusercontent.com/19414663/127767574-2da0a947-2511-4c5d-b8b1-12c263429348.png">
После первой операции с дробными числами программа сваливается в incorrect input при любых значениях на входе

2021-08-01 10:34 UTC, EitherNor commented
Все файлы программы не должны лежать просто в корне репозитория вразброс. В java принято именовать пакеты таким образом, чтобы составить уникальный путь (чтобы не пересекаться с другими библиотеками, где у классов названия могут совпадать) и так же нужно соблюдать структуру хранения исходников отдельно от ресурсов и прочих служебных файлов. Сделай структуру пакетов из корня репозитория в правильном виде и перемести туда все .java файлы, .gitignore остается наверху
/src/main/java    <-- это структура для хранения исходников, и далее:
                                         /com/ampp8800/calculator/    <-- это структура пакетов, образующая уникальный путь для твоего приложения

2021-08-01 10:57 UTC, EitherNor requested changes

2021-08-01 10:57 UTC, EitherNor commented on DataConversion.java
> +class DataConversion {
Суть этого класса в преобразовании входной строки в 3 переменные, необходимые для вычисления. По сути это класс-конвертер, его задача на вход принять одни данные и выдать их в другом виде. В таком случае нужно отделить логику конвертации от самих данных. Сделай отдельный класс для хранения нужных тебе данных. Этот предлагаю переименовать в `CalculationDataConverter` - название класса должно быть существительным, которое определяет, для чего нужен класс. У тебя называется `DataCoversion` - Какая data?  Неясно.  Conversion - это процесс, а не тот, кто его выполняет (это будет Converter). 
Так же конструкторы не должны содержать логики по возможности. Для этого есть методы. Конструкторы нужны для инициализации необходимые для работы класса данных. В твоем случае достаточно сделать в этом классе статический метод, который будет на вход принимать строку, а выдавать объект с нужными переменными. Никакого состояния этот класс хранить не должен

2021-08-01 10:57 UTC, EitherNor commented on Transformation.java
> +            for (int i = 0; i<5; i++){
Очень странная реализация округления, зачем такие сложности? Выше ты установил уже точность результата

2021-08-01 10:57 UTC, EitherNor commented on Transformation.java
> +    private Object result;
Зачем здесь тип Object?

2021-08-01 10:57 UTC, EitherNor commented on Transformation.java
> +    Transformation(BigDecimal data) {
В чем суть этого класса? Из названия только ясно, что происходит какая-то трансформация. Ситуация та же, что и в DataConversion - вынеси логику из конструктора в статический метод, который будет отдавать результат нужного типа, хранить состояние в этом классе незачем

2021-08-01 10:57 UTC, EitherNor commented on Сalculator.java
> +                while (true) {
А зачем здесь бесконечный цикл? В двух других у тебя читается ввод пользователя, а здесь?

2021-08-01 10:57 UTC, EitherNor commented on Сalculator.java
> +        } catch (IOException unused) {}
Если здесь упадет исключение - ты не узнаешь об этом. Всегда нужно собирать информацию об ошибках, в данном случае достаточно сделать `exception.printStackTrace();`

2021-08-01 10:57 UTC, EitherNor commented on Сalculator.java
> +    static BigDecimal calculation  (DataConversion data){
Неиспользуемый метод

2021-08-01 10:57 UTC, EitherNor commented on Transformation.java
> +            this.result = resultString;
Почему результат нужно хранить в виде строки? Ведь он имеет тип BigDecimal. В нужный момент всегда можно привести объект такого типа к строке

2021-08-03 18:17 UTC, ampp8800 commented on Transformation.java
> +    private Object result;
такая реализация на "1 + 1" выдаст "2.0000"

2021-08-03 18:40 UTC, ampp8800 commented on Сalculator.java
> +                while (true) {
первый бесконечный цикл{
бесконечный цикл1.1{ ввод данных для калькулятора }
бесконечный цикл1.2{ ввод данных для продолжения программы}
}

2021-08-03 18:43 UTC, ampp8800 commented on Сalculator.java
> +    static BigDecimal calculation  (DataConversion data){
в нем же как раз и происходит математические действия в зависимости от хранящихся в DataConversion данных

2021-08-03 18:44 UTC, ampp8800 commented on Transformation.java
> +            this.result = resultString;
так удобнее приводить "4.500" к "4.5", если необходимо результат выдавать именно в BigDecimal - переделаю

2021-08-03 19:24 UTC, ampp8800 commented on DataConversion.java
> +class DataConversion {
поправил

2021-08-03 19:25 UTC, ampp8800 commented on Transformation.java
> +    Transformation(BigDecimal data) {
поправил

2021-08-03 19:25 UTC, ampp8800 commented on Сalculator.java
> +        } catch (IOException unused) {}
поправил

2021-08-03 19:35 UTC, EitherNor commented on Transformation.java
> +    private Object result;
Но ведь достаточно хранить BigDecimal с указанной точностью в 4 знака и будет то же самое, но уже с нужным типом, а не непонятный Object

2021-08-03 19:43 UTC, EitherNor commented on Сalculator.java
> +                while (true) {
Можно обойтись 2 циклами, они нужны на каждый юзер инпут. Это не критично, но сложность кода должна быть как можно меньше, т.е. по возможности упрощать
while (true) { 
  //запрос выражения
  // читать строку
  // если ошибка - скипнуть шаг цикла
  // вычисления
  while (true) {
  // запрос продолжить?
  // читать строку
  //если ответ "да" - прервать цикл, если "нет" - выход из приложения, если ошибка - ничего не делать
  }
}

2021-08-07 08:16 UTC, EitherNor commented
Почитай про Java Code Conventions - в коде нужно применять определенное форматирование, отступы в блоках кода, пробелы между операциями и тд. Идея может сама применить форматирование выделенного текста на шорткат Ctrl + Alt + L

2021-08-07 08:48 UTC, EitherNor requested changes
Нужно поправить ошибки поведения программы и поработать над правильной структурой классов и методов

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +            if (!strData[1].equals("+") && !strData[1].equals("-") && !strData[1].equals("*") && !strData[1].equals("/")){throw new Exception();}
Логика на исключениях - плохая практика. Такой механизм работает медленнее, чем простая проверка if и возврат из метода если что-то не так. К тому же это сложнее читать, т.к. нужно отслеживать где кидается исключение и что делается в catch вместо просмотра одного блока if. Переделай все вручную брошенные исключения на if - else

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +            if (!strData[1].equals("+") && !strData[1].equals("-") && !strData[1].equals("*") && !strData[1].equals("/")){throw new Exception();}
Исключения нужны там, где дальнейшая нормальная работа приложения невозможна. У тебя же неверный ввод - вполне рабочая ситуация, так что исключения для этого в данном случае перебор

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +            BigDecimal maxDouble = new BigDecimal(Double.MAX_VALUE);
Убери отовсюду сравнения с `Double.MAX_VALUE`. Для BigDecimal это не помеха, незачем вводить искусственные ограничения, если их нет в условиях задачи

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +            if (currentDouble1.compareTo(maxDouble) == 1){throw new Exception();}
Эти операции не нужны

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/DataConversion.java
> +public class DataConversion {
Название класса буквально переводится как "конвертация данных". Как считаешь, хорошо подходит задаче класса или может как-то более понятно можно назвать? Можешь у Тани спрашивать правильный перевод твоих мыслей, если что

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Transformation.java
> +class Transformation {
1 - Ты не переделал логику из конструктора на метод.
2 - В этом классе буквально 1 строка кода, остальное закомменчено. Мне видится, что этот класс больше не нужен вообще, а точность выражения можно добавлять в том месте, где ты вычисляешь результат.
3 - По твоему вопросу, у тебя некорректное представление результата с нулями. Прочитай про метод BigDecimal.toPlainString и примени его перед к результату перед выводом пользователю

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Transformation.java
> +    private Object result;
По-прежнему неверный тип

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +        BigDecimal maxDouble = new BigDecimal(Double.MAX_VALUE);
Не нужно

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +            if (currentDouble.compareTo(maxDouble) == 1){
Удоли (и все что ниже такое же - тоже)

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                        if (bigDecimal.compareTo(maxDouble) == 1) {
Зачем ты меня ограничиваешь, я же просто хочу посчитать...Разве я так много прошу?

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +    DataConversion dataConversion (String str) {
Я в прошлой версии писал, метод может и должен быть статическим в данной задаче. Если ты создаешь экземпляр класса - значит он зачем-то нужен. Здесь он не нужен ни для чего, кроме как вызвать у него этот метод. При статическом методе экземпляр класса создавать не понадобится

2021-08-07 08:48 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CalculationDataConverter.java
> +    DataConversion dataConversion (String str) {
Название метода можно сделать более понятным, если использовать вместо существительного глагол. Даже гугл переводчик с русского нормально переведет в данном случае

2021-08-11 20:22 UTC, EitherNor requested changes

2021-08-11 20:22 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                    ConverterData converterData = new ConverterData();
Обсуждали же, что этот класс не хранит состояние. Его экземпляр не нужно создавать

2021-08-11 20:22 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                    Data data = converterData.dataConversion(reader.readLine());
И здесь ты вызовешь у него статический метод, без создания экземпляра

2021-08-11 20:22 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +    Data dataConversion(String str) {
`static`

2021-08-12 07:03 UTC, EitherNor approved these changes

2021-08-12 07:04 UTC, merged