Task 4 memory
ampp8800/calculator pull request #6
Opened 2021-08-23 11:11 UTC by ampp8800

Проверить выполненное задание, дать замечания или подтвердить готовность

2021-08-23 11:45 UTC, EitherNor commented
Общие замечания: низкая информативность вывода в консоль. 
Добавить:
Отображение, какое значение в какую ячейку сохранено вместо "add new cell"
1. При сохранении хранилища в файл выдать в консоль информацию об этом, что за файл, куда сохранен, то есть путь.
2. При вычитке файла из памяти написать, что считан такой-то файл хранилища (указать путь).
3. При каждом сообщении об ошибке помимо правильного формата операции калькулятора выдавать список доступных команд
4. Если произошла ошибка формата команды, но затем правильно введена команда remember - не дает запомнить результат последней операции, поправить.

2021-08-24 15:59 UTC, EitherNor requested changes

2021-08-24 15:59 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +    static void readFile() {
В отдельный класс эти 2 метода

2021-08-24 15:59 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +    static void recording(String strData[], Data data, BigDecimal bigDecimal) {
В отдельный класс этот метод и все, которые ниже - тоже

2021-08-24 15:59 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/MathematicalFunction.java
>                  case "!":
case (Procedure.FAC.getProcedure()), ниже тоже поправить, констант в произвольных местах быть не должно

2021-08-25 15:45 UTC, EitherNor requested changes

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                    if (!(MathematicalFunction.Procedure.REM.equals(data.getOp()) || MathematicalFunction.Procedure.SHOW.equals(data.getOp()) || MathematicalFunction.Procedure.DEL.equals(data.getOp()
1. Когда видишь, что у строка кода по длине превышает белую вертикальную полосу в идее - делай перенос строки. Слишком длинные строки невозможно читать.
2. У тебя здесь идет довольно уродливая логика определения, не является ли операция службной командой. 
Вместо этого можно добавить в енам еще одно поле - тип. Тогда вместо этой длинной строки у тебя будет одна проверка `if (ProcedureType.ТВОЙ_ТИП_ПРОЦЕДУРЫ.equals(data.getOp())`

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                if (MathematicalFunction.Procedure.REM.getProcedure().equalsIgnoreCase(strData[0])) {
У тебя здесь идет нарушение задачи, выполняемой классом. Он должен только определить что за операция поступила на вход и передать эти данные дальше в код для обработки, но ты здесь начинаешь обрабатывать команды. У тебя неконсистентная обработка команд в 2 местах, я даже запутался где что обрабатывается. Один тип операции (в данном случае - обработка команды, выполнение фактической операции) должен выполняться в одном месте. Вынеси отсюда лишнее

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    op = MathematicalFunction.Procedure.REM;
По сути этот тип не несет смысла, вместо него так же мог быть Null, тк обработка уже произошла и коду снаружи не нужна эта операция. (в дополнение к предыдущему комменту)

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/FileWorker.java
> +                Repository.setCell(line[0], bigDecimal);
Для работы с репозиторием у тебя есть класс RepositoryWorker. Он должен скрывать реализацию репозитория от остального кода, так что работай везде через него. Если надо, в него можно добавить простое прокидывание вызова без какой-то дополнительной логики

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/MathematicalFunction.java
> +        SUM(MathematicalFunction.SUM),
Здесь заменил на константу, а в остальных операциях нет

2021-08-25 15:45 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/MathematicalFunction.java
>                      return Procedure.EXIT;
Чтобы не дублировать, можно 2 кейса написать один над другим

2021-08-25 18:27 UTC, EitherNor requested changes

2021-08-25 18:27 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    Repository.removeRepository();
Убрать отсюда исполнение команды

2021-08-25 18:27 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    RepositoryWorker.help();
Отсюда тоже

2021-08-25 18:27 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/MathematicalFunction.java
> +    private static final String SUM = "+";
Константы поправь на полные слова, без сокращений

2021-08-27 17:01 UTC, ampp8800 commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                    if (!(MathematicalFunction.Procedure.REM.equals(data.getOp()) || MathematicalFunction.Procedure.SHOW.equals(data.getOp()) || MathematicalFunction.Procedure.DEL.equals(data.getOp()
по второму пункту, если сделать отдельную константу - то до нее case никогда не дойдет т.к. будет выбрасываться при более узком сравнение ("+" идем по case и выбрасываем константу SUM, до MATCH_FUNKTION никогда не дойдет)
скорее всего есть команда на проверку принадлежности к константам, но:
- error у меня является константой, хорошо переделали ее
- remember, removeall тоже константы, а значит нужно отработать их ввод -> еще более уродский if

2021-08-27 17:12 UTC, ampp8800 commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                if (MathematicalFunction.Procedure.REM.getProcedure().equalsIgnoreCase(strData[0])) {
не пойму, что конкретно не нравится?
op = MathematicalFunction.Procedure.REM; - окей, уберу в метод
if (MathematicalFunction.Procedure.REM.getProcedure().equalsIgnoreCase(strData[0]))  - можно тоже в отдельный метод убрать, но как по мне некрасиво и тогда уже else if (strData.length == 2) тоже в метод перенести нужно, нет?

2021-08-27 17:15 UTC, ampp8800 commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    op = MathematicalFunction.Procedure.REM;
он в классе Calculator используется для определения вызова метода же

2021-08-27 17:16 UTC, ampp8800 commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    op = MathematicalFunction.Procedure.REM;
офк тоже уродская хуйня

2021-08-27 17:19 UTC, ampp8800 commented on src/main/java/com/ampp8800/calculator/FileWorker.java
> +                Repository.setCell(line[0], bigDecimal);
ну мы таки передаем в метод из RepositoryWorker данные, что-то не выкупаю совсем

2021-08-27 17:29 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                if (MathematicalFunction.Procedure.REM.getProcedure().equalsIgnoreCase(strData[0])) {
Тут не про проверки речь, а про логику под ними

2021-08-27 17:33 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/ConverterData.java
> +                    op = MathematicalFunction.Procedure.REM;
Здесь имеется в виду, что конкретный тип операции не несет пользы в дальнейшем, только служит как маркер того, что операция "не математическая", что можно сделать гораздо проще, в том числе с нуллом (но это неправильно, не надо так), а так же что выполнение логики нужно отделить от определения типа процедуры, разделить на разные слои (классы). У тебя вся логика идет в классе Calculator, т.е. само выполнение математики. Обработку дополнительных команд можно вынести в другой класс, но исполняться они должны там же, где вызывается исполнение математических операций

2021-08-27 17:35 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/FileWorker.java
> +                Repository.setCell(line[0], bigDecimal);
Здесь ты напрямую в репозиторий передаешь данные из файла. Я имел в виду, что раз ты сделал класс RepositoryWorker, то пусть только он имеет право работать с самим репозиторием. У тебя не должна работа с репозитрием происходить где-то напрямую, а где-то в виде посредника RepositoryWorker. Либо везде напрямую, либо везде через посредника, если он нужен

2021-09-02 07:37 UTC, EitherNor requested changes

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Data.java
> +    private String str;
Что такое str? И где поле error, про которое говорили, чтобы передавать возможные ошибки наружу

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/UserStreamProcesson.java
> +                if (!Operation.CommandType.MATH.equals(op.getCommandType())) {
`op` может быть null, тогда при попытке получить команду падает NullPointerException, который ты ловишь в Calculator. Так лучше не делать, ведь у тебя есть другой механизм для передачи ошибок (поля в классе Data).
Если же ты специально хочешь бросить исключение в случае ошибки - это должно быть внятное исключение, а не NullPointerException (который говорит только о том, что ты накосячил где-то в коде и не сделал проверку на null)

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/UserStreamProcesson.java
> +            if (strData.length == 2) {
В каждой такой ветке if определяется какой-то конкретный сценарий и возвращается Data. Вынеси каждую ветку в отдельный метод с ясным названием, например 
```
if (strData.length == 3) { 
  data = getMathdata(strData) 
} else if (strData.lenght == 2 { 
  data = getServiceData(strData) 
} else if (strData.lenght == 1 { 
  data = getFactorialOrServiceData(strData) 
}
```

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Math.java
> +public class Math {
MathCommandProcessor или придумай получше, но явно не "Математика"

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/CommandProcessor.java
> +        if (Operation.CommandType.MATH.equals(data.getOp().getCommandType())) {
`data.getOp().getCommandType()` - может упасть NullPointerException

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Calculator.java
> +                data = UserStreamProcesson.inputData();
Что мешает после этой строчки проверить `op == null` ? Это позволяет избежать кучи исключений по всей программе, которые непонятно действительно предусмотрены логикой или твоя недоработка. Проверка ошибок, которые ты сам же и предусматриваешь логикой своей программы, всегда должна быть явной.

2021-09-02 07:37 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/UserStreamProcesson.java
> +                    op = null;
Похоже ты таким образом решил передавать ошибку. Окей, но ты нигде не проверяешь явно `if (op == null)' Логика проверки ошибок отсутствует, все сваливается с исключениями в разных местах и попадает в мейн класс в catch(Exception). Не надо так делать, проверяй явно `op == null` и обрабатывай ошибку

2021-09-02 07:40 UTC, EitherNor commented
Основные проблемы: 

1. Плохая работа с ошибками, нужно ввести явные проверки
2. Запутанный длинный код местами, разбить на методы с нормальными названиями
3. Кривые названия классов и методов, оставим на потом (не самая приоритетная проблема)

2021-09-09 17:39 UTC, EitherNor commented on src/main/java/com/ampp8800/calculator/Service.java
>          if (Operation.Command.REMEMBER.equals(data.getOp())) {
5 ифов? Замени на свитч

2021-09-10 07:27 UTC, EitherNor approved these changes

2021-09-10 07:28 UTC, merged